__title__ = 'spacyemoticon'
__version__ = '1.0.1'
__summary__ = 'spaCy pipeline component for adding emoticon meta data to Doc, Token and Span objects that are text emoticons.'
__uri__ = 'https://spacy.io'
__author__ = 'Raúl Escamilla'
__email__ = 'raul.escamilla@asesoriait.com'
__license__ = 'MIT'